### ISSUE TITLE
Checklist para prática 2 - GCMS

### ISSUE THREAD

**Issue by davidsonfe** [davidsonfe/GCMS-Davidson-Felix#2]
@ramidedantas
@davidsonfe 
Itens do checklist:
- [x]  Instalar Git localmente
- [x]  Criar projeto local
- [x]  Criar repositório local e realizar commits
- [ ]  Subir alterações para o repositório remoto
- [ ]  Fazer alterações no repositório da turma

**Comment by ramidedantas** [comment]
@davidsonfe, o checklist é como abaixo:

- [x] Tarefa 1
- [ ] Tarefa 2
- [ ] Tarefa 3

**Comment by ramidedantas** [comment]
@davidsonfe OK, deixar aberto.
